### ISSUE TITLE
Colaboration with project

### ISSUE THREAD

**Issue by ttortiz** [dlfraga/ManicomioShareCouchPotatoPlugin#1]
Hi, 
  Are you brazilian right? If not please repply me and i can talk in english.
I want to help on ManicomioShareCouchPotatoPlugin.

Olá amigo,
   Tenho interesse em ajudar a fazer o ManicomioShareCouchPotatoPlugin voltar a funcionar. Você já está trabalhando nisso? Sabe me direcionar os motivos que ele parou de funcionar?
  Pode me ensinar a melhor forma de debugar ele? É a primeira vez que mexo com raspberry e fazem anos que não trabalho com linux, então estou um pouco enferrujado.

O motivo dele ter parado é aquele captcha no login? Se for isso você chegou a pensar em alguma estratégia para resolver?

Obrigado pela atenção amigo,

Abração,
Thiago
ttortiz at gmail com

**Comment by dlfraga** [comment]
Olá!
Na real o plugin tinha alguns problemas já antes do recaptcha:
1) No login "as vezes" o site não permitia o logon do couchpotato. Era um problema bem bizarro que parecia ter a ver com o uso de cloudflare, fiquei um tempo tentando achar a solução mas como isso ia e vinha eu acabei convivendo com o problema;

2) O plugin fazia um parse manual das paginas do site e daí pegava os resultados e repassava ao couch. Isso apresentava alguns problemas quando o pessoal não seguia um padrão nos nomes dos filmes;

O que me motivou a colocar o aviso de que ele não funciona mais foi o recaptcha mesmo. 

As possíveis soluções:
1) Isso é um mistério, talvez seria necessário atrasar o processo de login ou forçar um refresh quando um cache é detectado, tentei várias coisas  e não rolou;
2) O site adicionou suporte a tags IMDB (que são as utilizadas pelo couch) daí a pesquisa agora poderia ser beeem mais simples. Teria que ser reescrita essa parte, resolveria todos os problemas de search;
3) O recaptcha complica. Eu não fui atrás de uma solução para isso ainda e como eu achei que ninguém usasse nem me estressei em tentar arrumar =P

Para fazer o debug do plugin é só ativar o debug no proprio couchpotato e dar um tail -f no log. As mensagens serão todas mostradas juntas e daí é bem simples a analise do que está rolando. 

Me dá uns dias que vou ver se tem uma forma de bypass do captcha ou de fazer o couch mostrar uma tela pedindo, sei lá. sem isso funcionando o resto basicamente se torna inutil.

**Comment by ttortiz** [comment]
Show Daniel,
  Precisando de ajuda dá um toque.

Assim que eu deixar meu raspberry do jeito que eu quero, vou subir a imagem
e a configuração pro github, aí quem sabe a gente consegue mais pessoas
usando seu plugin.

Abração e de qualquer forma vlw pela atenção

Em 13 de janeiro de 2017 20:43, Daniel Fraga <notifications@github.com>
escreveu:

**Comment by dlfraga** [comment]
A principio todos os problemas foram resolvidos no commit abaixo. O captcha está pedindo somente após tentativas de login erradas, então não é preciso tratar isso por enquanto.
Commit: f03f55fee0ad73b3e538b76f6921e0ce040dc9e6
Ainda existem alguns casos em que o plugin falha em encontrar os torrents, mas infelizmente isso se deve a variações do padrão utilizado nos nomes que aparecem no tracker, por exemplo, alguns filmes aparecem no tracker com o ano errado e por isso o couchpotato os ignora. 
Adicionalmente: A pesquisa por imdb id não é factivel por enquanto por que seria necessário entrar em cada torrent para validar a id.
