### ISSUE TITLE
Failed to Login to manicomio share.

### ISSUE THREAD

**Issue by feliro** [dlfraga/ManicomioShareCouchPotatoPlugin#3]
ERROR [ manicomioplugin] Failed to login ManicomioShare: unknown
ERROR[edia._base.providers.base] Failed to login to: ManicomioShare

I had using my name and my password to conect to manicomioshare via manicomioshare cp plugin.
What´s wrong?

**Comment by dlfraga** [comment]
I'm gonna try to reproduce the problem and get back to you. I've seen this happen sometimes because of missing cookies needed by cloudflare to allow the login process to work, I've implemented a method to overcome this before and maybe it's not working anymore.

**Comment by dlfraga** [comment]
Bug finally fixed along with many others!
